#!/usr/bin/env python3
"""Write per-service .env files for all services."""
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ENVS = {

"services/registry/.env": (
"# =============================================================================\n"
"# Registry Service — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"REGISTRY_HOST=0.0.0.0\n"
"REGISTRY_PORT=8000\n"
"HEARTBEAT_TIMEOUT=60\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_registry/.env": (
"# =============================================================================\n"
"# MCP Registry Service — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_REGISTRY_HOST=0.0.0.0\n"
"MCP_REGISTRY_PORT=8200\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_gateway/.env": (
"# =============================================================================\n"
"# MCP Gateway Service — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_GATEWAY_HOST=0.0.0.0\n"
"MCP_GATEWAY_PORT=8300\n"
"MCP_REGISTRY_URL=http://mcp-registry:8200\n"
"LOG_LEVEL=INFO\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# AWS Bedrock (REQUIRED for LLM routing)\n"
"# ----------------------------------------------------------------------------\n"
"AWS_ACCESS_KEY_ID=your_access_key_here\n"
"AWS_SECRET_ACCESS_KEY=your_secret_key_here\n"
"AWS_REGION=us-east-1\n"
"BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0\n"
),

"services/orchestrator/.env": (
"# =============================================================================\n"
"# Orchestrator Service — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"ORCHESTRATOR_NAME=MainOrchestrator\n"
"ORCHESTRATOR_PORT=8100\n"
"REGISTRY_URL=http://registry:8000\n"
"MCP_GATEWAY_URL=http://mcp-gateway:8300\n"
"LOG_LEVEL=INFO\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# AWS Bedrock (REQUIRED)\n"
"# ----------------------------------------------------------------------------\n"
"AWS_ACCESS_KEY_ID=your_access_key_here\n"
"AWS_SECRET_ACCESS_KEY=your_secret_key_here\n"
"AWS_SESSION_TOKEN=\n"
"AWS_REGION=us-east-1\n"
"BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# Workflow Features\n"
"# ----------------------------------------------------------------------------\n"
"ENABLE_PERSISTENCE=true\n"
"ENABLE_RETRY=true\n"
"MAX_RETRIES=3\n"
"ENABLE_PARALLEL=true\n"
"MAX_PARALLEL_STEPS=5\n"
"WORKFLOW_TIMEOUT=3600\n"
"STEP_TIMEOUT=300\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# Shared Workflow Database\n"
"# WORKFLOW_DB_BACKEND=postgresql requires DATABASE_URL to be set\n"
"# ----------------------------------------------------------------------------\n"
"WORKFLOW_DB_BACKEND=sqlite\n"
"DATABASE_URL=\n"
"SQLITE_DB_PATH=/app/data/workflows.db\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# HA / Multi-instance\n"
"# Set HA_BACKEND=redis to activate cross-instance shared state\n"
"# ----------------------------------------------------------------------------\n"
"HA_BACKEND=in_memory\n"
"REDIS_URL=redis://redis:6379\n"
"ORCHESTRATOR_INSTANCE_ID=\n"
"ORCHESTRATOR_PUBLIC_ENDPOINT=\n"
"OWNERSHIP_TTL=30\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# Vector Memory Store (long-term agent recall)\n"
"# Set VECTOR_MEMORY_ENABLED=true and choose a backend to activate\n"
"# ----------------------------------------------------------------------------\n"
"VECTOR_MEMORY_ENABLED=false\n"
"VECTOR_MEMORY_BACKEND=in_memory\n"
"VECTOR_MEMORY_EMBEDDING=bedrock\n"
"VECTOR_MEMORY_COLLECTION=a2a_memories\n"
"VECTOR_MEMORY_TOP_K=5\n"
"VECTOR_MEMORY_SCORE_THRESHOLD=0.3\n"
"VECTOR_MEMORY_MAX_ENTRIES=1000\n"
"VECTOR_MEMORY_PERSIST_PATH=\n"
"\n"
"# Bedrock embeddings (reuses AWS creds above)\n"
"BEDROCK_EMBED_MODEL=amazon.titan-embed-text-v1\n"
"\n"
"# AWS OpenSearch (VECTOR_MEMORY_BACKEND=opensearch_aws)\n"
"OPENSEARCH_HOST=\n"
"OPENSEARCH_SERVICE=es\n"
"OPENSEARCH_REGION=us-east-1\n"
"OPENSEARCH_INDEX=a2a-memories\n"
"OPENSEARCH_VECTOR_DIM=1536\n"
"\n"
"# Azure AI Search (VECTOR_MEMORY_BACKEND=azure_ai_search)\n"
"AZURE_SEARCH_ENDPOINT=\n"
"AZURE_SEARCH_API_KEY=\n"
"AZURE_SEARCH_INDEX=a2a-memories\n"
"\n"
"# Azure Cosmos DB (VECTOR_MEMORY_BACKEND=azure_cosmos)\n"
"COSMOS_ENDPOINT=\n"
"COSMOS_KEY=\n"
"COSMOS_DATABASE=a2a_agent_memory\n"
"COSMOS_CONTAINER=agent_memories\n"
"COSMOS_VECTOR_POLICY=diskANN\n"
"\n"
"# ChromaDB (VECTOR_MEMORY_BACKEND=chromadb)\n"
"CHROMA_HOST=\n"
"CHROMA_PORT=8000\n"
"CHROMA_PERSIST_PATH=/app/data/chroma\n"
"\n"
"# Qdrant (VECTOR_MEMORY_BACKEND=qdrant)\n"
"QDRANT_URL=\n"
"QDRANT_HOST=\n"
"QDRANT_PORT=6333\n"
"QDRANT_API_KEY=\n"
"\n"
"# Pinecone (VECTOR_MEMORY_BACKEND=pinecone)\n"
"PINECONE_API_KEY=\n"
"PINECONE_INDEX_NAME=a2a-memories\n"
"\n"
"# OpenAI embeddings (VECTOR_MEMORY_EMBEDDING=openai)\n"
"OPENAI_API_KEY=\n"
"OPENAI_EMBED_MODEL=text-embedding-3-small\n"
),

"services/agents/research_agent/.env": (
"# =============================================================================\n"
"# Research Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=ResearchAgent\n"
"AGENT_PORT=8003\n"
"REGISTRY_URL=http://registry:8000\n"
"MCP_GATEWAY_URL=http://mcp-gateway:8300\n"
"LOG_LEVEL=INFO\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# AWS Bedrock (REQUIRED)\n"
"# ----------------------------------------------------------------------------\n"
"AWS_ACCESS_KEY_ID=your_access_key_here\n"
"AWS_SECRET_ACCESS_KEY=your_secret_key_here\n"
"AWS_REGION=us-east-1\n"
"BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0\n"
),

"services/agents/code_analyzer/.env": (
"# =============================================================================\n"
"# Code Analyzer Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=CodeAnalyzer\n"
"AGENT_PORT=8001\n"
"REGISTRY_URL=http://registry:8000\n"
"LOG_LEVEL=INFO\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# AWS Bedrock (REQUIRED)\n"
"# ----------------------------------------------------------------------------\n"
"AWS_ACCESS_KEY_ID=your_access_key_here\n"
"AWS_SECRET_ACCESS_KEY=your_secret_key_here\n"
"AWS_SESSION_TOKEN=\n"
"AWS_REGION=us-east-1\n"
"BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0\n"
),

"services/agents/data_processor/.env": (
"# =============================================================================\n"
"# Data Processor Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=DataProcessor\n"
"AGENT_PORT=8002\n"
"REGISTRY_URL=http://registry:8000\n"
"LOG_LEVEL=INFO\n"
"\n"
"# ----------------------------------------------------------------------------\n"
"# AWS Bedrock (REQUIRED)\n"
"# ----------------------------------------------------------------------------\n"
"AWS_ACCESS_KEY_ID=your_access_key_here\n"
"AWS_SECRET_ACCESS_KEY=your_secret_key_here\n"
"AWS_SESSION_TOKEN=\n"
"AWS_REGION=us-east-1\n"
"BEDROCK_MODEL_ID=anthropic.claude-3-5-sonnet-20241022-v2:0\n"
),

"services/agents/task_executor/.env": (
"# =============================================================================\n"
"# Task Executor Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=TaskExecutor\n"
"AGENT_PORT=8004\n"
"REGISTRY_URL=http://registry:8000\n"
"LOG_LEVEL=INFO\n"
),

"services/agents/observer/.env": (
"# =============================================================================\n"
"# Observer Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=Observer\n"
"AGENT_PORT=8005\n"
"REGISTRY_URL=http://registry:8000\n"
"LOG_LEVEL=INFO\n"
),

"services/agents/math_agent/.env": (
"# =============================================================================\n"
"# Math Agent — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"AGENT_NAME=MathAgent\n"
"AGENT_PORT=8006\n"
"AGENT_HOST=0.0.0.0\n"
"PUBLIC_HOST=math-agent\n"
"REGISTRY_URL=http://registry:8000\n"
"MCP_GATEWAY_URL=http://mcp-gateway:8300\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_servers/calculator/.env": (
"# =============================================================================\n"
"# Calculator MCP Server — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_SERVER_NAME=CalculatorServer\n"
"MCP_SERVER_PORT=8213\n"
"MCP_REGISTRY_URL=http://mcp-registry:8200\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_servers/file_ops/.env": (
"# =============================================================================\n"
"# File Operations MCP Server — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_FILE_OPS_HOST=0.0.0.0\n"
"MCP_FILE_OPS_PORT=8210\n"
"MCP_REGISTRY_URL=http://mcp-registry:8200\n"
"WORKSPACE_DIR=/tmp/mcp_workspace\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_servers/database/.env": (
"# =============================================================================\n"
"# Database MCP Server — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_DATABASE_HOST=0.0.0.0\n"
"MCP_DATABASE_PORT=8211\n"
"MCP_REGISTRY_URL=http://mcp-registry:8200\n"
"DATABASE_PATH=/tmp/mcp_database.db\n"
"LOG_LEVEL=INFO\n"
),

"services/mcp_servers/web_search/.env": (
"# =============================================================================\n"
"# Web Search MCP Server — Runtime Configuration\n"
"# =============================================================================\n"
"\n"
"MCP_WEB_SEARCH_HOST=0.0.0.0\n"
"MCP_WEB_SEARCH_PORT=8212\n"
"MCP_REGISTRY_URL=http://mcp-registry:8200\n"
"LOG_LEVEL=INFO\n"
),

}

for rel, content in ENVS.items():
    path = os.path.join(BASE, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  written: {rel}")

print("\nAll done.")
